CREATE TABLE Player (
ID INT NOT NULL,
USERNAME VARCHAR(20) NOT NULL,
PASSWORD VARCHAR(40) NOT NULL,
NAME VARCHAR(40) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE Stats (
INT PLAYER ID NOT NULL,
INT EXP NOT NULL,
INT LEVEL NOT NULL,
INT WIN,
INT LOSS,
INT BOSS
PRIMARY KEY (ID)
);

CREATE TABLE CLASS (
INT PLAYER ID NOT NULL,
INT CLASS ID NOT NULL
);

INSERT INTO Player
VALUES (0, 'admin', 'admin', 'admin');
