CREATE TABLE Player (
ID INT NOT NULL,
USERNAME VARCHAR(20) NOT NULL,
PASSWORD VARCHAR(40) NOT NULL,
NAME VARCHAR(40) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE Stats (
PLAYER_ID INT NOT NULL,
EXP INT NOT NULL,
LEVEL INT NOT NULL,
WIN INT,
LOSS INT,
BOSS INT,
PRIMARY KEY (PLAYER_ID)
);

CREATE TABLE Class (
PLAYER_ID INT NOT NULL,
CLASS_ID INT NOT NULL
);

INSERT INTO Player
VALUES (0, 'admin', 'admin', 'admin');
